### ISSUE TITLE
AWS S3

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/WarpSQL#10]

**Comment by AtulRajput01** [comment]
I'm interested in contributing to the AWS S3 #10 I would like to request to be assigned this to me  as I am working on it and believe I can provide a valuable contribution.

**Comment by Mr-Sunglasses** [comment]
@ChakshuGautam I think there is no development by the active assigned person, Can I work on this issue ?

**Comment by ChakshuGautam** [comment]
Sure.

**Comment by ChakshuGautam** [comment]
@Mr-Sunglasses are you picking this up?

**Comment by Mr-Sunglasses** [comment]
@ChakshuGautam yes working on it, will do a PR by Sunday.

**Comment by AtulRajput01** [comment]
> @ChakshuGautam yes working on it, will do a PR by Sunday.

hii @Mr-Sunglasses are you working on it ?

**Comment by singhalkarun** [comment]
Referencing in master ticker, not tracking separately.
