### ISSUE TITLE
Implement versioning strategy

### ISSUE THREAD

**Issue by PiyushRaj927** [Samagra-Development/WarpSQL#117]
Currently, WarpSQL's versioning lacks a proper structure. It would be nice to formalize this process to alert users of breaking changes etc.

**Comment by PiyushRaj927** [comment]
## Proposal
I am proposing the following versioning strategy for the WarpSQL codebase, using the [SemVer Specification](https://semver.org/spec/v2.0.0.html#semantic-versioning-specification-semver).

### MAJOR Version (v1.x.x):
For incompatible backward changes.
Examples:
- Increment an extension to `MAJOR`versions
- Features causing backward incompatibility

### MINOR Version (vx.4.x):
For non-breaking feature additions.
Examples:
- Increment an extension to `MINOR`/`PATCH`versions
- Addition of an extension
- Upgrades maintaining backward compatibility

### PATCH Version (vx.x.1):
For bug fixes that are backward compatible.

Using this strategy, we can guarantee that upgrading to a `MINOR`/`PATCH`version of WarpSQL will ensure backward compatibility.

**Comment by singhalkarun** [comment]
How do we handle test/alpha releases?
