### ISSUE TITLE
Documentation: Compatibility Matrix

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/WarpSQL#13]
Add a table with X and Y axis being extensions and ticks and cross emojis to figure out what extension combinations would work for someone. Any subset of a row or column can be a valid combination.

**Comment by jayanth-kumar-morem** [comment]
Hey @ChakshuGautam ,
Can you please add more references to this Compatibility Matrix currently being used else where or some demos ?

**Comment by jayanth-kumar-morem** [comment]
Should this issue be blocking the other development issues or can I proceed with other issues ?

Also, I suggest we have a different workflow for this complete testing using the matrix and lets keep the smoke-tests workflow simple till the completion of development and once we have all the extensions implemented, we can drop the smoke-tests completely and use the workflow with the compatibility matrix for complete testing which takes much more time compared to smoke tests.

**Comment by ChakshuGautam** [comment]
Not a blocker. You can pick up others.

**Comment by fibonacci35813** [comment]
@ChakshuGautam I was just trying to produce this documentation, can you please explain on how can I see the compatibility amongst extension? Am I meant to see the compatibility of current extensions being used and then decide their respective compatibility with each other. If yes then do provide some context on how can I proceed with doing that?

**Comment by ChakshuGautam** [comment]
Wr can start with a manual one by just reading the docs. Long term this should be done using building the thing and then running smoke test to judge if it works or not.

**Comment by fibonacci35813** [comment]
> Add a table with X and Y axis being extensions and ticks and cross emojis to figure out what extension combinations would work for someone. Any subset of a row or column can be a valid combination.

Which all type of extensions should I be comparing?

**Comment by ChakshuGautam** [comment]
#2 is the master list. You can use the ones that are already done for the matrix.

**Comment by AK4266** [comment]
Hey can you assign this to me
