### ISSUE TITLE
Create extension pgvector failing

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/WarpSQL#14]
Ideally the extension should be available here - `/usr/local/share/postgresql/extension`
PgVector's Dockerfile - https://github.com/pgvector/pgvector/blob/master/Dockerfile

Update the smoke tests - https://github.com/Samagra-Development/WarpSQL/blob/e612601aa55114e1d2ff48f0081fa8a73579e941/.github/workflows/smoke-test.yml#L53

**Comment by singhalkarun** [comment]
.

**Comment by singhalkarun** [comment]
It is actually working fine, just that we were trying to find extension by different name. The extension is named "vector" by pgvector. @ChakshuGautam 

<img width="1198" alt="18" src="https://user-images.githubusercontent.com/113603846/233000170-e8e4be28-69c1-4de5-b51a-40c59e33b550.png">
<img width="1198" alt="19" src="https://user-images.githubusercontent.com/113603846/233000196-550a84b7-a870-4615-87c1-11646e34dd23.png">

**Comment by ChakshuGautam** [comment]
Aah my bad. Not sure what I was thinking.
