### ISSUE TITLE
Max Connection Limit as Env Variable

### ISSUE THREAD

**Issue by singhalkarun** [Samagra-Development/WarpSQL#18]

**Comment by thesilentline** [comment]
`{
  "provisioners": [
    {
      "type": "shell",
      "environment_vars": [
        "MAX_CONNECTIONS={{user `max_connections`}}"
      ],
      "script": "setup_script.sh"
    }
  ]
}
`

will this work?

**Comment by singhalkarun** [comment]
PR to be raised with #79
