### ISSUE TITLE
Master Tracker for Extension Support

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/WarpSQL#2]
WarpSQL wants to support the following extensions

- [x]  [PgVector](https://github.com/pgvector/pgvector)
- [x] [TimescaleDB](https://github.com/timescale/timescaledb)
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #10
- [ ] #34
- [x] #61 

Every single issue should have the following
1. Precise steps on how to add the extension to the Dockerfile
2. How to enable the extension
3. Actual smoke tests described in English
4. CI Updated with smoke tests
5. Build pipeline updates needed

**Comment by EeshNaugraiya** [comment]
hey I am interested in warps; and want to crack this issue. Can you please assign this to me

**Comment by ChakshuGautam** [comment]
Hey @EeshNaugraiya please start with individual issues mentioned in the list.

**Comment by Amrittttt** [comment]
Hey can you assign this to me?

**Comment by singhalkarun** [comment]
Tracking now in https://github.com/Samagra-Development/WarpSQL/issues/123, thus closing this ticket
