### ISSUE TITLE
Postgresml

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/WarpSQL#34]
- [ ] Evaluate [postgresml](https://github.com/postgresml/postgresml) and see if we can add this to WarpSQL.
- [ ] If yes for the above, add this.

**Comment by mynknight** [comment]
I am interested to work on Postgresml #34 can you assign me this

**Comment by ChakshuGautam** [comment]
Please go ahead!!

**Comment by thesilentline** [comment]
I am interested to work on this issue can you assign me @ChakshuGautam

**Comment by ChakshuGautam** [comment]
Hey @thesilentline please go ahead.
