### ISSUE TITLE
Packer template to setup a WarpSQL Instance

### ISSUE THREAD

**Issue by singhalkarun** [Samagra-Development/WarpSQL#51]
Reference: https://developer.hashicorp.com/packer/docs/templates/hcl_templates

Details:

1) A packer template that allows us to build WarpSQL image for multiple platforms like Docker, AWS EC2 AMI, Azure VMI, etc.
2) The template should be flexible enough. For ex. User should be able to configure extensions users want to enable may be in ENV or Config, and only those extensions should be setup.
3) Both of the above should be done for extensions which are currently enabled.

**Comment by thesilentline** [comment]
I am interested in working out this issue please assign me @singhalkarun

**Comment by thesilentline** [comment]
and please provide some further details regarding the issue
