### ISSUE TITLE
PLV8

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/WarpSQL#6]

**Comment by jayanth-kumar-morem** [comment]
Hey @ChakshuGautam , can you please assign me to this ?

**Comment by ChakshuGautam** [comment]
Please go ahead!!

**Comment by thesilentline** [comment]
can you please assign me to this? @ChakshuGautam

**Comment by jayanth-kumar-morem** [comment]
Hi @thesilentline , I have already started working on this, please check the other issues 😃

**Comment by singhalkarun** [comment]
Referencing in master issue, not tracking separately.
