### ISSUE TITLE
Static website using GitHub Pages showing details about the project. (Readme Content)

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/WarpSQL#67]
Readme Content to be shown on the home page for WarpSQL.

**Comment by inkerton** [comment]
> Readme Content to be shown on the home page for WarpSQL.

I would like to work on the issue. I just forked and cloned the repository but firstly it said checkout failed.
![image](https://github.com/Samagra-Development/WarpSQL/assets/127668005/45288242-2816-41ad-a443-0640419dab6f)

then on running 'git status' command all the files were staged and deleted.
![image](https://github.com/Samagra-Development/WarpSQL/assets/127668005/327fe75f-6999-42a4-a7b9-745f45072da4)
Is the problem with my system. I am currently restoring them but if you would satisfy my query .

**Comment by inkerton** [comment]
Created a Pull Request #95 .
Please review it.
