### ISSUE TITLE
PG Auto Failover

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/WarpSQL#8]
[This](https://pg-auto-failover.readthedocs.io/en/main/) plugin needs to be integrated to the project.

**Comment by fibonacci35813** [comment]
Hey @ChakshuGautam , Can you provide details regarding this issue?

**Comment by ChakshuGautam** [comment]
> Hey @ChakshuGautam , Can you provide details regarding this issue?

Added details.
